# -*- coding: utf-8 -*-
"""recommend_tags.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDnvm0RHTcna_kZ2TPeTV9NXaXjJDufm
"""

items = {
    "The Matrix": {"sci-fi", "action", "dystopian"},
    "Inception": {"sci-fi", "thriller", "mind-bending"},
    "The Notebook": {"romance", "drama"},
    "John Wick": {"action", "thriller"},
    "Interstellar": {"sci-fi", "drama", "space"},
    "La La Land": {"romance", "musical", "drama"},
    "Mad Max: Fury Road": {"action", "dystopian", "sci-fi"},
    "Titanic": {"romance", "drama", "tragedy"},
    "The Dark Knight": {"action", "thriller", "crime"},
    "Pride and Prejudice": {"romance", "drama", "period"},
    "Blade Runner 2049": {"sci-fi", "dystopian", "thriller"},
    "Gladiator": {"action", "drama", "historical"},
    "The Notebook 2": {"romance", "drama", "tragedy"},
    "Avengers: Endgame": {"action", "sci-fi", "adventure"},
    "A Quiet Place": {"thriller", "horror", "sci-fi"},
    "The Fault in Our Stars": {"romance", "drama", "tragedy"},
    "Dune": {"sci-fi", "adventure", "space"},
    "Get Out": {"horror", "thriller", "mystery"},
    "500 Days of Summer": {"romance", "drama", "comedy"},
    "Edge of Tomorrow": {"sci-fi", "action", "thriller"},
}
def get_user_preferences():
    """Take user input for interests."""
    print("Available tags:", sorted({tag for tags in items.values() for tag in tags}))
    raw = input("Enter your interests (comma-separated): ")
    prefs = {tag.strip().lower() for tag in raw.split(",") if tag.strip()}
    return prefs

def jaccard_similarity(set_a, set_b):
    """Calculate similarity between two sets of tags."""
    if not set_a or not set_b:
        return 0.0
    intersection = len(set_a & set_b)
    union = len(set_a | set_b)
    return intersection / union

def recommend(user_prefs, items, top_n=3):
    """Rank items by similarity score to user preferences."""
    scores = []
    for name, tags in items.items():
        score = jaccard_similarity(user_prefs, tags)
        if score > 0:
            scores.append((name, round(score, 2)))
    scores.sort(key=lambda x: x[1], reverse=True)
    return scores[:top_n]
def main():
    user_prefs = get_user_preferences()
    recommendations = recommend(user_prefs, items)

    print("\n--- Recommended For You ---")
    if recommendations:
        for name, score in recommendations:
            print(f"{name}  (match score: {score})")
    else:
        print("No matches found. Try different interests!")

if __name__ == "__main__":
    main()

