# -*- coding: utf-8 -*-
"""recommend_ratings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDnvm0RHTcna_kZ2TPeTV9NXaXjJDufm
"""

users_ratings = {
    "Alice": {
        "The Matrix": 5, "Inception": 4, "Titanic": 2, "La La Land": 1,
        "Interstellar": 5, "Gladiator": 3, "Dune": 4, "Get Out": 2,
        "John Wick": 3, "The Dark Knight": 4, "Pride and Prejudice": 2,
        "Blade Runner 2049": 5, "The Notebook 2": 1, "Avengers: Endgame": 4,
        "A Quiet Place": 3, "The Fault in Our Stars": 2, "Mad Max: Fury Road": 4,
        "Edge of Tomorrow": 5, "500 Days of Summer": 2, "The Notebook": 1
    },
    "Bob": {
        "The Matrix": 4, "Inception": 5, "Titanic": 1, "La La Land": 2,
        "Interstellar": 4, "Gladiator": 4, "Dune": 3, "Get Out": 3,
        "John Wick": 5, "The Dark Knight": 5, "Pride and Prejudice": 1,
        "Blade Runner 2049": 4, "The Notebook 2": 1, "Avengers: Endgame": 5,
        "A Quiet Place": 4, "The Fault in Our Stars": 1, "Mad Max: Fury Road": 5,
        "Edge of Tomorrow": 4, "500 Days of Summer": 2, "The Notebook": 1
    },
    "Carol": {
        "The Matrix": 2, "Inception": 3, "Titanic": 5, "La La Land": 4,
        "Interstellar": 2, "Gladiator": 2, "Dune": 2, "Get Out": 1,
        "John Wick": 1, "The Dark Knight": 2, "Pride and Prejudice": 5,
        "Blade Runner 2049": 2, "The Notebook 2": 5, "Avengers: Endgame": 2,
        "A Quiet Place": 1, "The Fault in Our Stars": 5, "Mad Max: Fury Road": 1,
        "Edge of Tomorrow": 2, "500 Days of Summer": 4, "The Notebook": 5
    },
    "Dave": {
        "The Matrix": 4, "Inception": 3, "Titanic": 2, "La La Land": 2,
        "Interstellar": 3, "Gladiator": 4, "Dune": 3, "Get Out": 2,
        "John Wick": 4, "The Dark Knight": 4, "Pride and Prejudice": 2,
        "Blade Runner 2049": 3, "The Notebook 2": 1, "Avengers: Endgame": 5,
        "A Quiet Place": 3, "The Fault in Our Stars": 2, "Mad Max: Fury Road": 5,
        "Edge of Tomorrow": 4, "500 Days of Summer": 2, "The Notebook": 1
    },
    "Eve": {
        "The Matrix": 3, "Inception": 4, "Titanic": 2, "La La Land": 2,
        "Interstellar": 4, "Gladiator": 2, "Dune": 5, "Get Out": 5,
        "John Wick": 2, "The Dark Knight": 3, "Pride and Prejudice": 2,
        "Blade Runner 2049": 4, "The Notebook 2": 1, "Avengers: Endgame": 3,
        "A Quiet Place": 5, "The Fault in Our Stars": 2, "Mad Max: Fury Road": 2,
        "Edge of Tomorrow": 3, "500 Days of Summer": 2, "The Notebook": 1
    },
    "Frank": {
        "The Matrix": 2, "Inception": 2, "Titanic": 4, "La La Land": 5,
        "Interstellar": 2, "Gladiator": 1, "Dune": 2, "Get Out": 1,
        "John Wick": 1, "The Dark Knight": 2, "Pride and Prejudice": 4,
        "Blade Runner 2049": 1, "The Notebook 2": 5, "Avengers: Endgame": 2,
        "A Quiet Place": 1, "The Fault in Our Stars": 4, "Mad Max: Fury Road": 1,
        "Edge of Tomorrow": 2, "500 Days of Summer": 3, "The Notebook": 4
    },
}

def get_new_user_ratings():
    """Collect ratings from the new user."""
    print("Rate these items (1-5). Press Enter to skip an item.")
    all_items = sorted({item for ratings in users_ratings.values() for item in ratings})
    new_ratings = {}
    for item in all_items:
        val = input(f"{item}: ").strip()
        if val.isdigit() and 1 <= int(val) <= 5:
            new_ratings[item] = int(val)
    return new_ratings

def cosine_similarity(ratings_a, ratings_b):
    """Compute similarity between two users based on shared rated items."""
    shared_items = set(ratings_a) & set(ratings_b)
    if not shared_items:
        return 0.0

    dot_product = sum(ratings_a[i] * ratings_b[i] for i in shared_items)
    mag_a = sum(ratings_a[i] ** 2 for i in shared_items) ** 0.5
    mag_b = sum(ratings_b[i] ** 2 for i in shared_items) ** 0.5

    if mag_a == 0 or mag_b == 0:
        return 0.0
    return dot_product / (mag_a * mag_b)

def recommend_from_ratings(new_user_ratings, users_ratings, top_n=3):
    """Find similar users, then recommend items the new user hasn't rated."""
    similarities = {
        user: cosine_similarity(new_user_ratings, ratings)
        for user, ratings in users_ratings.items()
    }
    sorted_neighbors = sorted(similarities.items(), key=lambda x: x[1], reverse=True)
    item_scores = {}
    for neighbor, sim in sorted_neighbors:
        if sim <= 0:
            continue
        for item, rating in users_ratings[neighbor].items():
            if item not in new_user_ratings:
                item_scores[item] = item_scores.get(item, 0) + rating * sim

    ranked = sorted(item_scores.items(), key=lambda x: x[1], reverse=True)
    return ranked[:top_n]

def main():
    new_user_ratings = get_new_user_ratings()
    recommendations = recommend_from_ratings(new_user_ratings, users_ratings)

    print("\n--- Recommended For You (Based on Similar Users) ---")
    if recommendations:
        for item, score in recommendations:
            print(f"{item}  (weighted score: {round(score, 2)})")
    else:
        print("Not enough data to recommend. Try rating more items!")

if __name__ == "__main__":
    main()

